language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

deploy:
  provider: pypi
  #username: evdh
  username: "__token__"
  password: $PYPI_PASSWORD #Added pypi token to environment on travis-ci
  edge: true # opt in to dpl v2
  #server:  https://test.pypi.org/legacy/ #Test server of PyPi
  server:  https://upload.pypi.org/legacy/
  skip_existing: true #see https://docs.travis-ci.com/user/deployment/pypi/#upload-artifacts-only-once
  on:
    tags: true